# Generated by Django 4.2 on 2024-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='url',
            field=models.FileField(upload_to='', verbose_name='文章封面地址'),
        ),
    ]
