# Generated by Django 4.2 on 2024-08-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cover_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('email', models.EmailField(max_length=64, verbose_name='邮箱')),
                ('site_url', models.CharField(max_length=32, verbose_name='网站链接')),
                ('addr', models.CharField(max_length=16, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '网站基础信息',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '新闻速览'), (2, '游玩'), (3, '其他')], null=True, verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='url',
            field=models.FileField(upload_to='article_img/', verbose_name='文章封面地址'),
        ),
    ]
