# Generated by Django 4.2 on 2024-08-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_siteinfo_alter_articles_category_alter_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='word',
        ),
    ]
