# Generated by Django 4.2 on 2024-08-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_articles_comment_count_remove_articles_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='show',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
    ]
