# Generated by Django 4.2 on 2024-08-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='img_list',
        ),
        migrations.AlterField(
            model_name='advert',
            name='img',
            field=models.URLField(blank=True, help_text='单图', null=True, verbose_name='图片地址'),
        ),
    ]
