# Generated by Django 4.2 on 2024-08-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_advert_img_list_alter_advert_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='addr',
            field=models.TextField(blank=True, null=True, verbose_name='用户地址信息'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ip',
            field=models.GenericIPAddressField(default='120.228.2.238', verbose_name='ip地址'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='qq_num',
            field=models.TextField(blank=True, null=True, verbose_name='QQ号码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=0, verbose_name='用户性别'),
        ),
    ]
