# Generated by Django 4.2 on 2024-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_userinfo_avatar_alter_userinfo_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImg',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='site_bgimg/', verbose_name='图片地址')),
                ('dominant_hue', models.CharField(blank=True, max_length=16, null=True, verbose_name='封面主色调')),
                ('is_dark', models.BooleanField(blank=True, null=True, verbose_name='是否是深色系')),
            ],
            options={
                'verbose_name_plural': '站点背景图',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('menu_title', models.CharField(max_length=16, null=True, verbose_name='菜单名称')),
                ('menu_title_en', models.CharField(max_length=32, null=True, verbose_name='菜单英文名称')),
                ('title', models.CharField(max_length=32, null=True, verbose_name='slogan')),
                ('abstract', models.TextField(help_text='多个之间按分号区分', null=True, verbose_name='slogan介绍')),
                ('abstract_time', models.IntegerField(default=4, help_text='单位秒，默认是8秒', verbose_name='slogan切换时间')),
                ('rotation', models.BooleanField(default=True, verbose_name='是否轮播slogan介绍')),
                ('menu_rotation', models.BooleanField(default=False, help_text='多选默认会轮播', verbose_name='是否轮播banner图')),
                ('menu_time', models.IntegerField(default=8, help_text='单位秒，默认是8秒', verbose_name='背景图切换时间')),
                ('menu_url', models.ManyToManyField(help_text='可以多选，多选就会轮播', to='app.menuimg', verbose_name='菜单图片')),
            ],
            options={
                'verbose_name_plural': '站点背景',
            },
        ),
    ]
