# Generated by Django 4.2 on 2024-08-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_menuimg_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_rotation',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_title_en',
        ),
        migrations.AlterField(
            model_name='menu',
            name='abstract',
            field=models.TextField(help_text='多个之间按分号区分', null=True, verbose_name='文字介绍'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='abstract_time',
            field=models.IntegerField(default=4, help_text='单位秒，默认是8秒', verbose_name='文字切换时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=32, null=True, verbose_name='文字'),
        ),
    ]
