# Generated by Django 4.2 on 2024-08-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_menu_menu_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavTags',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=16, verbose_name='标签名称')),
            ],
            options={
                'verbose_name_plural': '网站标签',
            },
        ),
        migrations.AlterField(
            model_name='menu',
            name='rotation',
            field=models.BooleanField(default=True, verbose_name='是否轮播文字介绍'),
        ),
        migrations.CreateModel(
            name='SiteNav',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='网站标题')),
                ('abstract', models.CharField(max_length=128, null=True, verbose_name='网站简介')),
                ('href', models.URLField(verbose_name='网站链接')),
                ('icon_href', models.URLField(blank=True, help_text='在线链接', null=True, verbose_name='图标链接')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('tag', models.ManyToManyField(to='app.navtags', verbose_name='网站标签')),
            ],
            options={
                'verbose_name_plural': '网站导航',
            },
        ),
    ]
