# Generated by Django 4.2 on 2024-08-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_navtags_alter_menu_rotation_sitenav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navtags',
            options={'verbose_name_plural': '网站导航标签'},
        ),
        migrations.AddField(
            model_name='navtags',
            name='iconText',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='标签图标'),
        ),
        migrations.AlterField(
            model_name='navtags',
            name='title',
            field=models.CharField(max_length=16, verbose_name='网站标签名称'),
        ),
    ]
