# Generated by Django 4.2 on 2024-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_navtags_options_navtags_icontext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='nameObj',
            field=models.CharField(blank=True, max_length=64, verbose_name='美名'),
        ),
    ]
