# Generated by Django 4.2 on 2024-08-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_siteinfo_email_siteinfo_nameobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ip',
        ),
    ]
