# Generated by Django 4.2 on 2024-08-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_userinfo_addr_remove_userinfo_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='real_title',
            field=models.CharField(max_length=32, null=True, verbose_name='网站名字'),
        ),
    ]
