# Generated by Django 4.2 on 2024-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_advert_real_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtags',
            name='iconText',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标签图标'),
        ),
        migrations.AlterField(
            model_name='navtags',
            name='title',
            field=models.CharField(max_length=32, verbose_name='网站标签名称'),
        ),
    ]
